channel = "openEuler-24.03-LTS"
arch = ["aarch64", "x86_64"]
[repos.OS]
baseurl = "https://repo.openeuler.org/openEuler-24.03-LTS/OS"
[repos.update]
baseurl = "https://repo.openeuler.org/openEuler-24.03-LTS/update"
watch_update = true
[repos.everything]
baseurl = "https://repo.openeuler.org/openEuler-24.03-LTS/everything"
[job]
os = "openeuler"
os_version = "24.03-LTS"