#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "compass-ci-web"

load_cci_defaults

/usr/bin/docker build --no-cache -t epkg_repo_nginx .


