name: Checkstyle

on: [pull_request, workflow_dispatch]

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/pycodestyle-action@0.1.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
